In [1]:
# import dependencies
import pandas as pd
import datetime

# 2017-market-data

In [2]:
# read in 2017 market prices
market_2017 = pd.read_csv("raw/2017-market-region-hab-data.csv")
market_2017.head()

,Geography,Segment,Variety,Timeframe,Period,Current Year Week Ending,Units Prior Year,Units Current Year,Unit Variance,Dollars Prior Year,Dollars Current Year,Dollar Variance,ASP Prior Year,ASP Current Year,ASP Variance
0,Albany,Avocados,Hass,Last 04 Wks,1,1/29/2017 0:00,407688.25,414997.59,0.017929,474096.20,526144.34,0.109784,1.162889,1.267825,0.090237
1,Albany,Avocados,Hass,Last 04 Wks,2,2/26/2017 0:00,464174.45,474327.41,0.021873,484448.36,643283.21,0.327867,1.043677,1.356201,0.299445
2,Albany,Avocados,Hass,Last 04 Wks,3,3/26/2017 0:00,412013.41,428197.68,0.039281,492765.05,536982.97,0.089734,1.195993,1.254054,0.048546
3,Albany,Avocados,Hass,Last 04 Wks,4,4/23/2017 0:00,427319.20,388241.62,-0.091448,496838.57,557034.31,0.121158,1.162687,1.434762,0.234005
4,Albany,Avocados,Hass,Last 04 Wks,5,5/21/2017 0:00,502563.73,473973.05,-0.056890,527758.58,587504.68,0.113207,1.050133,1.239532,0.180357

In [3]:
# rename columns
market_2017.columns = ["geography", "segment", "variety", "timeframe", "period", "date", "units_prior_year",
                       "units_current_year", "unit_variance", "dollars_prior_year", "dollars_current_year",
                       "dollar_variance", "avg_price_prior_year", "avg_price_current_year", "avg_price_variance"]

# change type to lowercase
market_2017.loc[:,"segment"] = market_2017.loc[:,"segment"].str.lower()
market_2017.loc[:,"variety"] = market_2017.loc[:,"variety"].str.lower()
market_2017.loc[:,"timeframe"] = market_2017.loc[:,"timeframe"].str.lower()

cols = list(market_2017.columns.values)
cols

['geography',
 'segment',
 'variety',
 'timeframe',
 'period',
 'date',
 'units_prior_year',
 'units_current_year',
 'unit_variance',
 'dollars_prior_year',
 'dollars_current_year',
 'dollar_variance',
 'avg_price_prior_year',
 'avg_price_current_year',
 'avg_price_variance']

In [4]:
# add year_month column and move to first column
market_2017['year_month'] = market_2017['date']
market_2017 = market_2017[['year_month',
                             'geography',
                             'segment',
                             'variety',
                             'timeframe',
                             'period',
                             'date',
                             'units_prior_year',
                             'units_current_year',
                             'unit_variance',
                             'dollars_prior_year',
                             'dollars_current_year',
                             'dollar_variance',
                             'avg_price_prior_year',
                             'avg_price_current_year',
                             'avg_price_variance']]
market_2017.head()

,year_month,geography,segment,variety,timeframe,period,date,units_prior_year,units_current_year,unit_variance,dollars_prior_year,dollars_current_year,dollar_variance,avg_price_prior_year,avg_price_current_year,avg_price_variance
0,1/29/2017 0:00,Albany,avocados,hass,last 04 wks,1,1/29/2017 0:00,407688.25,414997.59,0.017929,474096.20,526144.34,0.109784,1.162889,1.267825,0.090237
1,2/26/2017 0:00,Albany,avocados,hass,last 04 wks,2,2/26/2017 0:00,464174.45,474327.41,0.021873,484448.36,643283.21,0.327867,1.043677,1.356201,0.299445
2,3/26/2017 0:00,Albany,avocados,hass,last 04 wks,3,3/26/2017 0:00,412013.41,428197.68,0.039281,492765.05,536982.97,0.089734,1.195993,1.254054,0.048546
3,4/23/2017 0:00,Albany,avocados,hass,last 04 wks,4,4/23/2017 0:00,427319.20,388241.62,-0.091448,496838.57,557034.31,0.121158,1.162687,1.434762,0.234005
4,5/21/2017 0:00,Albany,avocados,hass,last 04 wks,5,5/21/2017 0:00,502563.73,473973.05,-0.056890,527758.58,587504.68,0.113207,1.050133,1.239532,0.180357

In [5]:
# check column dtypes
market_2017.dtypes

year_month                 object
geography                  object
segment                    object
variety                    object
timeframe                  object
period                      int64
date                       object
units_prior_year          float64
units_current_year        float64
unit_variance             float64
dollars_prior_year        float64
dollars_current_year      float64
dollar_variance           float64
avg_price_prior_year      float64
avg_price_current_year    float64
avg_price_variance        float64
dtype: object

In [6]:
# change date to datetime format
market_2017[['year_month', "date"]] = market_2017[['year_month', "date"]].apply(pd.to_datetime)
market_2017.dtypes

year_month                datetime64[ns]
geography                         object
segment                           object
variety                           object
timeframe                         object
period                             int64
date                      datetime64[ns]
units_prior_year                 float64
units_current_year               float64
unit_variance                    float64
dollars_prior_year               float64
dollars_current_year             float64
dollar_variance                  float64
avg_price_prior_year             float64
avg_price_current_year           float64
avg_price_variance               float64
dtype: object

In [7]:
# change year_month format
market_2017["year_month"] = pd.to_datetime(market_2017["year_month"]).dt.to_period("m")
market_2017

,year_month,geography,segment,variety,timeframe,period,date,units_prior_year,units_current_year,unit_variance,dollars_prior_year,dollars_current_year,dollar_variance,avg_price_prior_year,avg_price_current_year,avg_price_variance
0,2017-01,Albany,avocados,hass,last 04 wks,1,2017-01-29,4.076882e+05,4.149976e+05,0.017929,4.740962e+05,5.261443e+05,0.109784,1.162889,1.267825,0.090237
1,2017-02,Albany,avocados,hass,last 04 wks,2,2017-02-26,4.641745e+05,4.743274e+05,0.021873,4.844484e+05,6.432832e+05,0.327867,1.043677,1.356201,0.299445
2,2017-03,Albany,avocados,hass,last 04 wks,3,2017-03-26,4.120134e+05,4.281977e+05,0.039281,4.927650e+05,5.369830e+05,0.089734,1.195993,1.254054,0.048546
3,2017-04,Albany,avocados,hass,last 04 wks,4,2017-04-23,4.273192e+05,3.882416e+05,-0.091448,4.968386e+05,5.570343e+05,0.121158,1.162687,1.434762,0.234005
4,2017-05,Albany,avocados,hass,last 04 wks,5,2017-05-21,5.025637e+05,4.739730e+05,-0.056890,5.277586e+05,5.875047e+05,0.113207,1.050133,1.239532,0.180357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,2017-01,Syracuse,avocados,hass,last 04 wks,13,2017-01-01,2.129520e+05,2.308022e+05,0.083823,2.674745e+05,3.022927e+05,0.130174,1.256032,1.309748,0.042766
752,2017-01,Tampa,avocados,hass,last 04 wks,13,2017-01-01,1.391738e+06,1.537539e+06,0.104762,1.458080e+06,1.730076e+06,0.186544,1.047669,1.125224,0.074027
753,2017-01,Total U.S.,avocados,hass,last 04 wks,13,2017-01-01,1.175953e+08,1.224831e+08,0.041565,1.144707e+08,1.275742e+08,0.114470,0.973429,1.041565,0.069996
754,2017-01,West,avocados,hass,last 04 wks,13,2017-01-01,2.133227e+07,2.256529e+07,0.057801,1.980292e+07,2.259926e+07,0.141209,0.928308,1.001505,0.078850
755,2017-01,West Tex/New Mexico,avocados,hass,last 04 wks,13,2017-01-01,3.025971e+06,3.100917e+06,0.024767,2.288681e+06,2.356616e+06,0.029683,0.756346,0.759974,0.004797

In [8]:
# check column dtypes
market_2017.dtypes

year_month                     period[M]
geography                         object
segment                           object
variety                           object
timeframe                         object
period                             int64
date                      datetime64[ns]
units_prior_year                 float64
units_current_year               float64
unit_variance                    float64
dollars_prior_year               float64
dollars_current_year             float64
dollar_variance                  float64
avg_price_prior_year             float64
avg_price_current_year           float64
avg_price_variance               float64
dtype: object

In [9]:
# export market_2017
market_2017.to_csv('resources/market_2017.csv', index=False)

# 2018-market-data

In [10]:
# read in 2018 market prices
market_2018 = pd.read_csv("raw/2018-market-region-hab-data.csv")
market_2018.head()

,Geography,Segment,Variety,Timeframe,Period,Current Year Week Ending,Units Prior Year,Units Current Year,Unit Variance,Dollars Prior Year,Dollars Current Year,Dollar Variance,ASP Prior Year,ASP Current Year,ASP Variance
0,Albany,Avocados,Hass,Last 04 Wks,1,1/28/2018 0:00,414997.59,441313.06,0.063411,526144.34,560090.98,0.064520,1.267825,1.269147,0.001042
1,Albany,Avocados,Hass,Last 04 Wks,2,2/25/2018 0:00,474327.41,545814.07,0.150712,643283.21,727521.80,0.130951,1.356201,1.332911,-0.017173
2,Albany,Avocados,Hass,Last 04 Wks,3,3/25/2018 0:00,428197.68,545890.39,0.274856,536982.97,630076.44,0.173364,1.254054,1.154218,-0.079611
3,Albany,Avocados,Hass,Last 04 Wks,4,4/22/2018 0:00,388241.62,561508.32,0.446286,557034.31,618994.11,0.111232,1.434762,1.102377,-0.231665
4,Albany,Avocados,Hass,Last 04 Wks,5,5/20/2018 0:00,473973.05,663024.40,0.398865,587504.68,687736.85,0.170607,1.239532,1.037272,-0.163174

In [11]:
# rename columns
market_2018.columns = ["geography", "segment", "variety", "timeframe", "period", "date", "units_prior_year",
                       "units_current_year", "unit_variance", "dollars_prior_year", "dollars_current_year",
                       "dollar_variance", "avg_price_prior_year", "avg_price_current_year", "avg_price_variance"]

# change type to lowercase
market_2018.loc[:,"segment"] = market_2018.loc[:,"segment"].str.lower()
market_2018.loc[:,"variety"] = market_2018.loc[:,"variety"].str.lower()
market_2018.loc[:,"timeframe"] = market_2018.loc[:,"timeframe"].str.lower()

cols = list(market_2018.columns.values)
cols

['geography',
 'segment',
 'variety',
 'timeframe',
 'period',
 'date',
 'units_prior_year',
 'units_current_year',
 'unit_variance',
 'dollars_prior_year',
 'dollars_current_year',
 'dollar_variance',
 'avg_price_prior_year',
 'avg_price_current_year',
 'avg_price_variance']

In [12]:
# add year_month column and move to first column
market_2018['year_month'] = market_2018['date']
market_2018 = market_2018[['year_month',
                             'geography',
                             'segment',
                             'variety',
                             'timeframe',
                             'period',
                             'date',
                             'units_prior_year',
                             'units_current_year',
                             'unit_variance',
                             'dollars_prior_year',
                             'dollars_current_year',
                             'dollar_variance',
                             'avg_price_prior_year',
                             'avg_price_current_year',
                             'avg_price_variance']]
market_2018.head()

,year_month,geography,segment,variety,timeframe,period,date,units_prior_year,units_current_year,unit_variance,dollars_prior_year,dollars_current_year,dollar_variance,avg_price_prior_year,avg_price_current_year,avg_price_variance
0,1/28/2018 0:00,Albany,avocados,hass,last 04 wks,1,1/28/2018 0:00,414997.59,441313.06,0.063411,526144.34,560090.98,0.064520,1.267825,1.269147,0.001042
1,2/25/2018 0:00,Albany,avocados,hass,last 04 wks,2,2/25/2018 0:00,474327.41,545814.07,0.150712,643283.21,727521.80,0.130951,1.356201,1.332911,-0.017173
2,3/25/2018 0:00,Albany,avocados,hass,last 04 wks,3,3/25/2018 0:00,428197.68,545890.39,0.274856,536982.97,630076.44,0.173364,1.254054,1.154218,-0.079611
3,4/22/2018 0:00,Albany,avocados,hass,last 04 wks,4,4/22/2018 0:00,388241.62,561508.32,0.446286,557034.31,618994.11,0.111232,1.434762,1.102377,-0.231665
4,5/20/2018 0:00,Albany,avocados,hass,last 04 wks,5,5/20/2018 0:00,473973.05,663024.40,0.398865,587504.68,687736.85,0.170607,1.239532,1.037272,-0.163174

In [13]:
# check column dtypes
market_2018.dtypes

year_month                 object
geography                  object
segment                    object
variety                    object
timeframe                  object
period                      int64
date                       object
units_prior_year          float64
units_current_year        float64
unit_variance             float64
dollars_prior_year        float64
dollars_current_year      float64
dollar_variance           float64
avg_price_prior_year      float64
avg_price_current_year    float64
avg_price_variance        float64
dtype: object

In [14]:
# change date to datetime format
market_2018[['year_month', "date"]] = market_2018[['year_month', "date"]].apply(pd.to_datetime)
market_2018.dtypes

year_month                datetime64[ns]
geography                         object
segment                           object
variety                           object
timeframe                         object
period                             int64
date                      datetime64[ns]
units_prior_year                 float64
units_current_year               float64
unit_variance                    float64
dollars_prior_year               float64
dollars_current_year             float64
dollar_variance                  float64
avg_price_prior_year             float64
avg_price_current_year           float64
avg_price_variance               float64
dtype: object

In [15]:
# change year_month format
market_2018["year_month"] = pd.to_datetime(market_2018["year_month"]).dt.to_period("m")
market_2018

,year_month,geography,segment,variety,timeframe,period,date,units_prior_year,units_current_year,unit_variance,dollars_prior_year,dollars_current_year,dollar_variance,avg_price_prior_year,avg_price_current_year,avg_price_variance
0,2018-01,Albany,avocados,hass,last 04 wks,1,2018-01-28,414997.59,441313.06,0.063411,526144.34,560090.98,0.064520,1.267825,1.269147,0.001042
1,2018-02,Albany,avocados,hass,last 04 wks,2,2018-02-25,474327.41,545814.07,0.150712,643283.21,727521.80,0.130951,1.356201,1.332911,-0.017173
2,2018-03,Albany,avocados,hass,last 04 wks,3,2018-03-25,428197.68,545890.39,0.274856,536982.97,630076.44,0.173364,1.254054,1.154218,-0.079611
3,2018-04,Albany,avocados,hass,last 04 wks,4,2018-04-22,388241.62,561508.32,0.446286,557034.31,618994.11,0.111232,1.434762,1.102377,-0.231665
4,2018-05,Albany,avocados,hass,last 04 wks,5,2018-05-20,473973.05,663024.40,0.398865,587504.68,687736.85,0.170607,1.239532,1.037272,-0.163174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,2018-09,West Tex/New Mexico,avocados,hass,last 04 wks,9,2018-09-09,3029453.68,3349250.59,0.105563,3323213.50,3320133.95,-0.000927,1.096968,0.991307,-0.096321
698,2018-10,West Tex/New Mexico,avocados,hass,last 04 wks,10,2018-10-07,2573490.00,2965186.48,0.152204,3093944.58,3079366.47,-0.004712,1.202237,1.038507,-0.136188
699,2018-11,West Tex/New Mexico,avocados,hass,last 04 wks,11,2018-11-04,3025801.07,3097741.76,0.023776,3046102.82,2926691.87,-0.039201,1.006710,0.944782,-0.061514
700,2018-12,West Tex/New Mexico,avocados,hass,last 04 wks,12,2018-12-02,2994368.85,2551323.92,-0.147959,2742236.20,2459337.99,-0.103163,0.915798,0.963946,0.052575
701,2018-12,West Tex/New Mexico,avocados,hass,last 04 wks,13,2018-12-30,3102153.37,3065046.46,-0.011962,2791081.13,2926716.55,0.048596,0.899724,0.954869,0.061291

In [16]:
# check column dtypes
market_2018.dtypes

year_month                     period[M]
geography                         object
segment                           object
variety                           object
timeframe                         object
period                             int64
date                      datetime64[ns]
units_prior_year                 float64
units_current_year               float64
unit_variance                    float64
dollars_prior_year               float64
dollars_current_year             float64
dollar_variance                  float64
avg_price_prior_year             float64
avg_price_current_year           float64
avg_price_variance               float64
dtype: object

In [17]:
# export market_2018
market_2018.to_csv('resources/market_2018.csv', index=False)

# 2019-market-data

In [18]:
# read in 2019 market prices
market_2019 = pd.read_csv("raw/2019-market-region-hab-data.csv")
market_2019.head()

,Geography,Segment,Variety,Timeframe,Period,Current Year Week Ending,Units Prior Year,Units Current Year,Unit Variance,Dollars Prior Year,Dollars Current Year,Dollar Variance,ASP Prior Year,ASP Current Year,ASP Variance
0,California,Avocados,Hass,Last 04 Wks,1,1/6/2019 0:00,24643875.85,29370491.67,0.19,29413687.49,31421462.15,0.07,1.193550,1.069831,-0.10
1,Great Lakes,Avocados,Hass,Last 04 Wks,1,1/6/2019 0:00,17398324.82,19014870.07,0.09,20399196.67,19467894.65,-0.05,1.172481,1.023825,-0.13
2,Midsouth,Avocados,Hass,Last 04 Wks,1,1/6/2019 0:00,15387766.69,17984940.39,0.17,18584830.24,19227934.33,0.04,1.207767,1.069113,-0.12
3,Northeast,Avocados,Hass,Last 04 Wks,1,1/6/2019 0:00,21181739.70,24394834.55,0.15,28201009.92,30086378.99,0.07,1.331383,1.233309,-0.07
4,Plains,Avocados,Hass,Last 04 Wks,1,1/6/2019 0:00,9069072.68,9924781.46,0.09,10427112.67,10515116.45,0.01,1.149744,1.059481,-0.08

In [19]:
# rename columns
market_2019.columns = ["geography", "segment", "variety", "timeframe", "period", "date", "units_prior_year",
                       "units_current_year", "unit_variance", "dollars_prior_year", "dollars_current_year",
                       "dollar_variance", "avg_price_prior_year", "avg_price_current_year", "avg_price_variance"]

# change type to lowercase
market_2019.loc[:,"segment"] = market_2019.loc[:,"segment"].str.lower()
market_2019.loc[:,"variety"] = market_2019.loc[:,"variety"].str.lower()
market_2019.loc[:,"timeframe"] = market_2019.loc[:,"timeframe"].str.lower()

cols = list(market_2019.columns.values)
cols

['geography',
 'segment',
 'variety',
 'timeframe',
 'period',
 'date',
 'units_prior_year',
 'units_current_year',
 'unit_variance',
 'dollars_prior_year',
 'dollars_current_year',
 'dollar_variance',
 'avg_price_prior_year',
 'avg_price_current_year',
 'avg_price_variance']

In [20]:
# add year_month column and move to first column
market_2019['year_month'] = market_2019['date']
market_2019 = market_2019[['year_month',
                             'geography',
                             'segment',
                             'variety',
                             'timeframe',
                             'period',
                             'date',
                             'units_prior_year',
                             'units_current_year',
                             'unit_variance',
                             'dollars_prior_year',
                             'dollars_current_year',
                             'dollar_variance',
                             'avg_price_prior_year',
                             'avg_price_current_year',
                             'avg_price_variance']]
market_2019.head()

,year_month,geography,segment,variety,timeframe,period,date,units_prior_year,units_current_year,unit_variance,dollars_prior_year,dollars_current_year,dollar_variance,avg_price_prior_year,avg_price_current_year,avg_price_variance
0,1/6/2019 0:00,California,avocados,hass,last 04 wks,1,1/6/2019 0:00,24643875.85,29370491.67,0.19,29413687.49,31421462.15,0.07,1.193550,1.069831,-0.10
1,1/6/2019 0:00,Great Lakes,avocados,hass,last 04 wks,1,1/6/2019 0:00,17398324.82,19014870.07,0.09,20399196.67,19467894.65,-0.05,1.172481,1.023825,-0.13
2,1/6/2019 0:00,Midsouth,avocados,hass,last 04 wks,1,1/6/2019 0:00,15387766.69,17984940.39,0.17,18584830.24,19227934.33,0.04,1.207767,1.069113,-0.12
3,1/6/2019 0:00,Northeast,avocados,hass,last 04 wks,1,1/6/2019 0:00,21181739.70,24394834.55,0.15,28201009.92,30086378.99,0.07,1.331383,1.233309,-0.07
4,1/6/2019 0:00,Plains,avocados,hass,last 04 wks,1,1/6/2019 0:00,9069072.68,9924781.46,0.09,10427112.67,10515116.45,0.01,1.149744,1.059481,-0.08

In [21]:
# check column dtypes
market_2019.dtypes

year_month                 object
geography                  object
segment                    object
variety                    object
timeframe                  object
period                      int64
date                       object
units_prior_year          float64
units_current_year        float64
unit_variance             float64
dollars_prior_year        float64
dollars_current_year      float64
dollar_variance           float64
avg_price_prior_year      float64
avg_price_current_year    float64
avg_price_variance        float64
dtype: object

In [22]:
# change date to datetime format
market_2019[['year_month', "date"]] = market_2019[['year_month', "date"]].apply(pd.to_datetime)
market_2019.dtypes

year_month                datetime64[ns]
geography                         object
segment                           object
variety                           object
timeframe                         object
period                             int64
date                      datetime64[ns]
units_prior_year                 float64
units_current_year               float64
unit_variance                    float64
dollars_prior_year               float64
dollars_current_year             float64
dollar_variance                  float64
avg_price_prior_year             float64
avg_price_current_year           float64
avg_price_variance               float64
dtype: object

In [23]:
# change year_month format
market_2019["year_month"] = pd.to_datetime(market_2019["year_month"]).dt.to_period("m")
market_2019

,year_month,geography,segment,variety,timeframe,period,date,units_prior_year,units_current_year,unit_variance,dollars_prior_year,dollars_current_year,dollar_variance,avg_price_prior_year,avg_price_current_year,avg_price_variance
0,2019-01,California,avocados,hass,last 04 wks,1,2019-01-06,24643875.85,29370491.67,0.190000,29413687.49,31421462.15,0.070000,1.193550,1.069831,-0.100000
1,2019-01,Great Lakes,avocados,hass,last 04 wks,1,2019-01-06,17398324.82,19014870.07,0.090000,20399196.67,19467894.65,-0.050000,1.172481,1.023825,-0.130000
2,2019-01,Midsouth,avocados,hass,last 04 wks,1,2019-01-06,15387766.69,17984940.39,0.170000,18584830.24,19227934.33,0.040000,1.207767,1.069113,-0.120000
3,2019-01,Northeast,avocados,hass,last 04 wks,1,2019-01-06,21181739.70,24394834.55,0.150000,28201009.92,30086378.99,0.070000,1.331383,1.233309,-0.070000
4,2019-01,Plains,avocados,hass,last 04 wks,1,2019-01-06,9069072.68,9924781.46,0.090000,10427112.67,10515116.45,0.010000,1.149744,1.059481,-0.080000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,2019-12,Spokane,avocados,hass,last 04 wks,13,2019-12-29,352119.95,413437.48,0.174138,433343.07,435596.88,0.005201,1.230669,1.053598,-0.143882
698,2019-12,St. Louis,avocados,hass,last 04 wks,13,2019-12-29,700290.08,670929.99,-0.041926,867598.61,746727.37,-0.139317,1.238913,1.112974,-0.101653
699,2019-12,Syracuse,avocados,hass,last 04 wks,13,2019-12-29,300992.22,309279.61,0.027534,348902.32,334520.90,-0.041219,1.159174,1.081613,-0.066910
700,2019-12,Tampa,avocados,hass,last 04 wks,13,2019-12-29,2088112.90,2389629.09,0.144396,2166225.17,2056170.86,-0.050805,1.037408,0.860456,-0.170571
701,2019-12,West Tex/New Mexico,avocados,hass,last 04 wks,13,2019-12-29,3065046.46,3411949.52,0.113180,2926716.55,2893780.92,-0.011253,0.954869,0.848131,-0.111782

In [24]:
# check column dtypes
market_2019.dtypes

year_month                     period[M]
geography                         object
segment                           object
variety                           object
timeframe                         object
period                             int64
date                      datetime64[ns]
units_prior_year                 float64
units_current_year               float64
unit_variance                    float64
dollars_prior_year               float64
dollars_current_year             float64
dollar_variance                  float64
avg_price_prior_year             float64
avg_price_current_year           float64
avg_price_variance               float64
dtype: object

In [25]:
# export market_2019
market_2019.to_csv('resources/market_2019.csv', index=False)

# 2020-market-data

In [26]:
# read in 2020 market prices
market_2020 = pd.read_csv("raw/2020-market-region-hab-data.csv")
market_2020.head()

,Geography,Segment,Variety,Timeframe,Period,Current Year Week Ending,Units Prior Year,Units Current Year,Unit Variance,Dollars Prior Year,Dollars Current Year,Dollar Variance,ASP Prior Year,ASP Current Year,ASP Variance
0,California,Avocados,Hass,Last 04 Wks,1,1/26/2020 0:00,29370491.67,28311217.04,-0.036066,31421462.15,32580574.41,0.036889,1.069831,1.150801,0.075685
1,Great Lakes,Avocados,Hass,Last 04 Wks,1,1/26/2020 0:00,19014870.07,19696175.34,0.035830,19467894.65,18625709.19,-0.043260,1.023825,0.945651,-0.076355
2,Midsouth,Avocados,Hass,Last 04 Wks,1,1/26/2020 0:00,17984940.39,18155641.86,0.009491,19227934.33,18535197.49,-0.036028,1.069113,1.020906,-0.045091
3,Northeast,Avocados,Hass,Last 04 Wks,1,1/26/2020 0:00,24394834.55,25000503.93,0.024828,30086378.99,30089693.01,0.000110,1.233309,1.203563,-0.024119
4,Plains,Avocados,Hass,Last 04 Wks,1,1/26/2020 0:00,9924781.46,9289036.12,-0.064056,10515116.45,9556103.56,-0.091203,1.059481,1.028751,-0.029005

In [27]:
# rename columns
market_2020.columns = ["geography", "segment", "variety", "timeframe", "period", "date", "units_prior_year",
                       "units_current_year", "unit_variance", "dollars_prior_year", "dollars_current_year",
                       "dollar_variance", "avg_price_prior_year", "avg_price_current_year", "avg_price_variance"]

# change type to lowercase
market_2020.loc[:,"segment"] = market_2020.loc[:,"segment"].str.lower()
market_2020.loc[:,"variety"] = market_2020.loc[:,"variety"].str.lower()
market_2020.loc[:,"timeframe"] = market_2020.loc[:,"timeframe"].str.lower()

cols = list(market_2020.columns.values)
cols

['geography',
 'segment',
 'variety',
 'timeframe',
 'period',
 'date',
 'units_prior_year',
 'units_current_year',
 'unit_variance',
 'dollars_prior_year',
 'dollars_current_year',
 'dollar_variance',
 'avg_price_prior_year',
 'avg_price_current_year',
 'avg_price_variance']

In [28]:
# add year_month column and move to first column
market_2020['year_month'] = market_2020['date']
market_2020 = market_2020[['year_month',
                             'geography',
                             'segment',
                             'variety',
                             'timeframe',
                             'period',
                             'date',
                             'units_prior_year',
                             'units_current_year',
                             'unit_variance',
                             'dollars_prior_year',
                             'dollars_current_year',
                             'dollar_variance',
                             'avg_price_prior_year',
                             'avg_price_current_year',
                             'avg_price_variance']]
market_2020.head()

,year_month,geography,segment,variety,timeframe,period,date,units_prior_year,units_current_year,unit_variance,dollars_prior_year,dollars_current_year,dollar_variance,avg_price_prior_year,avg_price_current_year,avg_price_variance
0,1/26/2020 0:00,California,avocados,hass,last 04 wks,1,1/26/2020 0:00,29370491.67,28311217.04,-0.036066,31421462.15,32580574.41,0.036889,1.069831,1.150801,0.075685
1,1/26/2020 0:00,Great Lakes,avocados,hass,last 04 wks,1,1/26/2020 0:00,19014870.07,19696175.34,0.035830,19467894.65,18625709.19,-0.043260,1.023825,0.945651,-0.076355
2,1/26/2020 0:00,Midsouth,avocados,hass,last 04 wks,1,1/26/2020 0:00,17984940.39,18155641.86,0.009491,19227934.33,18535197.49,-0.036028,1.069113,1.020906,-0.045091
3,1/26/2020 0:00,Northeast,avocados,hass,last 04 wks,1,1/26/2020 0:00,24394834.55,25000503.93,0.024828,30086378.99,30089693.01,0.000110,1.233309,1.203563,-0.024119
4,1/26/2020 0:00,Plains,avocados,hass,last 04 wks,1,1/26/2020 0:00,9924781.46,9289036.12,-0.064056,10515116.45,9556103.56,-0.091203,1.059481,1.028751,-0.029005

In [29]:
# check column dtypes
market_2020.dtypes

year_month                 object
geography                  object
segment                    object
variety                    object
timeframe                  object
period                      int64
date                       object
units_prior_year          float64
units_current_year        float64
unit_variance             float64
dollars_prior_year        float64
dollars_current_year      float64
dollar_variance           float64
avg_price_prior_year      float64
avg_price_current_year    float64
avg_price_variance        float64
dtype: object

In [30]:
# change date to datetime format
market_2020[['year_month', "date"]] = market_2020[['year_month', "date"]].apply(pd.to_datetime)
market_2020.dtypes

year_month                datetime64[ns]
geography                         object
segment                           object
variety                           object
timeframe                         object
period                             int64
date                      datetime64[ns]
units_prior_year                 float64
units_current_year               float64
unit_variance                    float64
dollars_prior_year               float64
dollars_current_year             float64
dollar_variance                  float64
avg_price_prior_year             float64
avg_price_current_year           float64
avg_price_variance               float64
dtype: object

In [31]:
# change year_month format
market_2020["year_month"] = pd.to_datetime(market_2020["year_month"]).dt.to_period("m")
market_2020

,year_month,geography,segment,variety,timeframe,period,date,units_prior_year,units_current_year,unit_variance,dollars_prior_year,dollars_current_year,dollar_variance,avg_price_prior_year,avg_price_current_year,avg_price_variance
0,2020-01,California,avocados,hass,last 04 wks,1,2020-01-26,29370491.67,28311217.04,-0.036066,31421462.15,32580574.41,0.036889,1.069831,1.150801,0.075685
1,2020-01,Great Lakes,avocados,hass,last 04 wks,1,2020-01-26,19014870.07,19696175.34,0.035830,19467894.65,18625709.19,-0.043260,1.023825,0.945651,-0.076355
2,2020-01,Midsouth,avocados,hass,last 04 wks,1,2020-01-26,17984940.39,18155641.86,0.009491,19227934.33,18535197.49,-0.036028,1.069113,1.020906,-0.045091
3,2020-01,Northeast,avocados,hass,last 04 wks,1,2020-01-26,24394834.55,25000503.93,0.024828,30086378.99,30089693.01,0.000110,1.233309,1.203563,-0.024119
4,2020-01,Plains,avocados,hass,last 04 wks,1,2020-01-26,9924781.46,9289036.12,-0.064056,10515116.45,9556103.56,-0.091203,1.059481,1.028751,-0.029005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,2020-09,Spokane,avocados,hass,last 04 wks,9,2020-09-06,351836.38,538579.48,0.530767,566237.94,631711.42,0.115629,1.609379,1.172921,-0.271196
482,2020-09,St. Louis,avocados,hass,last 04 wks,9,2020-09-06,847987.07,1084121.37,0.278465,1110354.67,1025346.34,-0.076560,1.309400,0.945786,-0.277696
483,2020-09,Syracuse,avocados,hass,last 04 wks,9,2020-09-06,318909.46,416775.50,0.306877,432835.08,441290.38,0.019535,1.357235,1.058820,-0.219870
484,2020-09,Tampa,avocados,hass,last 04 wks,9,2020-09-06,2142073.96,2538142.16,0.184899,2226453.50,2210341.55,-0.007237,1.039392,0.870850,-0.162154
485,2020-09,West Tex/New Mexico,avocados,hass,last 04 wks,9,2020-09-06,3268452.46,4800684.01,0.468794,3717653.37,3766062.83,0.013022,1.137435,0.784485,-0.310304

In [32]:
# check column dtypes
market_2020.dtypes

year_month                     period[M]
geography                         object
segment                           object
variety                           object
timeframe                         object
period                             int64
date                      datetime64[ns]
units_prior_year                 float64
units_current_year               float64
unit_variance                    float64
dollars_prior_year               float64
dollars_current_year             float64
dollar_variance                  float64
avg_price_prior_year             float64
avg_price_current_year           float64
avg_price_variance               float64
dtype: object

In [33]:
# export market_2020
market_2020.to_csv('resources/market_2020.csv', index=False)