In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os
import warnings
warnings.filterwarnings('ignore')
from pathlib import Path

In [2]:
cleaned_df = pd.read_csv(Path('../resources/combined_cleaned.csv'))
cleaned_df.head()

,Unnamed: 0,index,type,avg_price,total_volume_price,4046_units,4225_units,4770_units,total_bags,s_bags,...,geography_South Carolina,geography_South Central,geography_Southeast,geography_Spokane,geography_St. Louis,geography_Syracuse,geography_Tampa,geography_Total U.S.,geography_West,geography_West Tex/New Mexico
0,0,5616,1,1.42,95246.38,2897.41,76570.67,44.00,15734.30,10012.80,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,5617,0,1.47,4140.95,7.30,301.87,0.00,3831.78,3831.78,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,5618,1,1.69,135196.35,3133.37,116520.88,88.78,15453.32,10023.79,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,5619,0,1.54,3346.54,14.67,253.01,0.00,3078.86,3078.86,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,5620,1,1.57,93625.03,3101.17,74627.23,55.59,15841.04,11614.79,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
cleaned_df = cleaned_df.drop(columns=['Unnamed: 0', 'index'], axis=1)
cleaned_df.head()

,type,avg_price,total_volume_price,4046_units,4225_units,4770_units,total_bags,s_bags,l_bags,xl_bags,...,geography_South Carolina,geography_South Central,geography_Southeast,geography_Spokane,geography_St. Louis,geography_Syracuse,geography_Tampa,geography_Total U.S.,geography_West,geography_West Tex/New Mexico
0,1,1.42,95246.38,2897.41,76570.67,44.00,15734.30,10012.80,5721.50,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,1.47,4140.95,7.30,301.87,0.00,3831.78,3831.78,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,1.69,135196.35,3133.37,116520.88,88.78,15453.32,10023.79,5429.53,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,1.54,3346.54,14.67,253.01,0.00,3078.86,3078.86,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,1.57,93625.03,3101.17,74627.23,55.59,15841.04,11614.79,4159.58,66.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
price_bins = [0.44, 1.14, 1.37, 1.63, 3.17]
group_names = ["0", "1", "2", "3" ]

cleaned_cat_df = cleaned_df.copy()

# Categorize prices for NB.
cleaned_cat_df["price_cat"] = pd.cut(cleaned_cat_df['avg_price'], price_bins, labels=group_names)

cleaned_cat_df.head()

,type,avg_price,total_volume_price,4046_units,4225_units,4770_units,total_bags,s_bags,l_bags,xl_bags,...,geography_South Central,geography_Southeast,geography_Spokane,geography_St. Louis,geography_Syracuse,geography_Tampa,geography_Total U.S.,geography_West,geography_West Tex/New Mexico,price_cat
0,1,1.42,95246.38,2897.41,76570.67,44.00,15734.30,10012.80,5721.50,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
1,0,1.47,4140.95,7.30,301.87,0.00,3831.78,3831.78,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
2,1,1.69,135196.35,3133.37,116520.88,88.78,15453.32,10023.79,5429.53,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
3,0,1.54,3346.54,14.67,253.01,0.00,3078.86,3078.86,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
4,1,1.57,93625.03,3101.17,74627.23,55.59,15841.04,11614.79,4159.58,66.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2

In [5]:
cleaned_cat_df['price_cat'].value_counts()

0    4282
1    3838
2    3681
3    3039
Name: price_cat, dtype: int64

In [6]:
cleaned_cat_df.columns

Index(['type', 'avg_price', 'total_volume_price', '4046_units', '4225_units',
       '4770_units', 'total_bags', 's_bags', 'l_bags', 'xl_bags',
       ...
       'geography_South Central', 'geography_Southeast', 'geography_Spokane',
       'geography_St. Louis', 'geography_Syracuse', 'geography_Tampa',
       'geography_Total U.S.', 'geography_West',
       'geography_West Tex/New Mexico', 'price_cat'],
      dtype='object', length=267)

In [8]:
cleaned_cat_df.shape

(14840, 267)

In [9]:
def RFSSModel4(X, y):
    # Initial imports.
    import pandas as pd
    from path import Path
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.preprocessing import StandardScaler
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
    
    # Splitting into Train and Test sets.
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)
    
    # Creating a StandardScaler instance.
    scaler = StandardScaler()
    # Fitting the Standard Scaler with the training data.
    X_scaler = scaler.fit(X_train)
    
    # Scaling the data.
    X_train_scaled = X_scaler.transform(X_train)
    X_test_scaled = X_scaler.transform(X_test)
    
    # Create a random forest classifier.
    #rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 
    rf_model = RandomForestClassifier(n_estimators=1024, random_state=78, max_depth=5) 
    
    # Fitting the model
    rf_model = rf_model.fit(X_train_scaled, y_train)
    
    # Making predictions using the testing data.
    predictions = rf_model.predict(X_test_scaled)
    
    print(f"Predictions: {predictions}")
    
    # Calculating the confusion matrix.
    cm = confusion_matrix(y_test, predictions)
    
    # Create a DataFrame from the confusion matrix.
    cm_df = pd.DataFrame(cm, index=["Actual 0", "Actual 1", "Actual 2", "Actual 3"], 
                         columns=["Predicted 0", "Predicted 1", "Predicted 2", "Predicted 3"])
    cm_df
    
    # Calculating the accuracy score.
    acc_score = accuracy_score(y_test, predictions)
    
    # Displaying results
    print("Confusion Matrix")
    display(cm_df)
    print(f"Accuracy Score : {acc_score}")
    print("Classification Report")
    print(classification_report(y_test, predictions))
    
    # Calculate feature importance in the Random Forest model.
    importances = rf_model.feature_importances_
    print(f"Importances: {importances}")
    
    # We can sort the features by their importance.
    print(sorted(zip(rf_model.feature_importances_, X.columns), reverse=True))

In [10]:
y = cleaned_cat_df['price_cat']
X = cleaned_cat_df.drop(columns=['price_cat', 'total_volume_prod', 'total_volume_price'], axis=1)

RFSSModel4(X, y)

Predictions: ['2' '0' '3' ... '2' '0' '2']
Confusion Matrix

          Predicted 0  Predicted 1  Predicted 2  Predicted 3
Actual 0          974           15           39            5
Actual 1           68          642          227           13
Actual 2           14          178          740           39
Actual 3            4           22           36          694

Accuracy Score : 0.8221024258760108
Classification Report
              precision    recall  f1-score   support

           0       0.92      0.94      0.93      1033
           1       0.75      0.68      0.71       950
           2       0.71      0.76      0.74       971
           3       0.92      0.92      0.92       756

    accuracy                           0.82      3710
   macro avg       0.83      0.82      0.82      3710
weighted avg       0.82      0.82      0.82      3710

Importances: [4.36197080e-02 3.06348645e-01 7.96838929e-02 4.17820227e-02
 5.89422673e-02 5.45278732e-02 4.34861178e-02 3.74548750e-02
 7.47235749e-02 2.48165256e-03 3.19582550e-03 4.03326885e-03
 7.21207756e-03 1.23984693e-03 6.53251148e-03 3.92172990e-03
 3.32797299e-03 9.36167737e-04 1.40289302e-03 3.11889083e-03
 5.31057351e-03 7.62008491e-03 4.39179922e-03 1.84783654e-03
 4.16125387e-03 3.66403604e-03 0.00000000e+00 2.33014474e-03
 1.08006047e-03 2.88168721e-03 4.08171474e-03 4.69385336e-04
 0.00000000e+00 0.00000000e+00 1.73314376e-03 7.65467416e-03
 8.69378640e-03 1.05658437e-02 1.00208962e-02 1.02259948e-02
 4.45807671e-03 1.93199168e-02 6.53161628e-02 1.53460704e-02
 3.37367873e-05 3.84094533e-05 8.66366484e-06 4.60034658e-05
 2.57565185e-05 1.76407084e-05 9.63380521e-06 3.48903760e-05
 3.49779725e-04 3.01737913e-05 4.03895103e-05 9.85404410e-05
 7.68732660e-06 9.99039916e-05 1.54859523e-04 6.13519721e-05
 1.85203077e-04 9.15478695e-05 2.04989435e-03 4.87120348e-04
 8.67756603e-05 1.29051350e-04 1.05796911e-04 3.44172795e-04
 7.43999297e-05 1.90217371e-04 6.78167255e-05 5.47604656e-05
 8.78220246e-06 1.53126632e-05 2.27471044e-05 3.17802683e-04
 1.38158686e-05 1.11337773e-05 3.03442851e-05 9.88387224e-06
 7.36245102e-06 1.29506689e-05 7.52119958e-06 1.20658337e-05
 1.12464725e-05 1.02419217e-05 1.46004912e-06 6.66790555e-06
 4.70818313e-06 1.30823139e-05 5.54181003e-06 9.90487728e-07
 8.16226278e-06 6.55496202e-06 2.31531601e-05 2.45423448e-06
 0.00000000e+00 3.30403548e-06 2.17226763e-06 0.00000000e+00
 0.00000000e+00 8.63846183e-06 1.77283535e-06 1.04048220e-06
 0.00000000e+00 2.92848978e-06 1.34215588e-05 5.96259105e-07
 1.36317295e-06 2.13026040e-06 5.65992305e-06 7.20432393e-05
 2.36188791e-05 4.27029196e-06 7.19363976e-06 1.09240580e-05
 6.94420911e-06 4.92103018e-06 8.25547579e-06 4.05159797e-06
 2.18012598e-06 4.37622961e-06 7.77302676e-06 3.77046612e-05
 1.31347638e-04 3.53718919e-06 4.51870827e-06 9.99767694e-06
 1.22258453e-05 1.05469343e-05 1.05477233e-05 5.17714006e-07
 6.67328949e-06 3.12067222e-06 7.50614022e-06 9.66426301e-06
 2.23779416e-06 1.03691510e-05 1.68732263e-05 3.77308476e-05
 1.23226139e-04 1.33936425e-05 1.13254349e-05 5.30762689e-06
 1.44242935e-05 2.23219068e-05 1.25444398e-05 1.17181309e-05
 3.06322317e-05 2.08569295e-05 2.46207160e-05 2.86599325e-05
 1.44117138e-04 3.58016010e-05 2.84328185e-05 1.63793823e-05
 5.66510133e-06 1.28966716e-05 2.96646553e-06 3.74467945e-06
 7.93604621e-06 3.61348884e-06 5.04779980e-06 1.15710981e-05
 7.66865643e-06 6.40036217e-06 3.39885142e-05 2.70844158e-05
 5.78942954e-06 1.12125473e-05 1.26335434e-05 2.71760319e-05
 2.45594086e-05 1.97329330e-05 4.66976662e-06 4.22696288e-05
 5.73583954e-06 8.17040344e-06 3.27005726e-06 1.19734107e-05
 1.48727239e-05 7.65038338e-06 1.41100718e-05 9.91233456e-06
 1.57349594e-05 1.33129135e-05 9.97332879e-07 3.43184068e-06
 5.93296776e-06 1.19665448e-05 9.18858346e-07 2.47179245e-06
 4.27626326e-06 2.22429841e-06 1.12613141e-05 7.38444823e-06
 5.77963426e-06 2.03471923e-06 3.10382516e-06 1.73755805e-06
 3.39095154e-06 0.00000000e+00 7.67053638e-06 0.00000000e+00
 9.60787609e-06 5.24127811e-06 1.40909951e-06 1.00807887e-05
 9.35498257e-06 1.06032271e-05 1.38924767e-05 2.13020444e-04
 1.58993382e-04 6.57743966e-04 5.18446862e-04 7.42502309e-04
 4.18652099e-04 9.75259688e-04 2.84843244e-04 2.90657894e-04
 5.84350807e-05 2.48673075e-04 4.66241042e-04 3.06347472e-05
 5.98677598e-05 6.36189334e-04 1.23239892e-04 2.51096920e-04
 1.79233653e-03 7.90884506e-04 1.06103278e-04 1.43380052e-04
 5.12769794e-05 1.08997020e-04 2.45510782e-04 1.18561506e-04
 1.15763471e-04 6.21682627e-04 1.01915370e-03 1.25292930e-03
 7.89773276e-05 1.43719197e-04 4.78179125e-04 2.62311172e-04
 3.31755327e-04 1.21733306e-04 5.50784515e-04 5.11684978e-04
 1.77547735e-04 6.69773395e-05 2.52896435e-04 4.20813916e-04
 2.30627659e-03 1.00062895e-03 2.54947909e-05 4.16529014e-04
 1.01062630e-04 9.36509649e-04 4.46195266e-04 4.28599865e-04
 5.95384730e-04 8.51616942e-04 2.98634430e-04 4.86884911e-04]
[(0.306348644756774, 'avg_price'), (0.0796838929256686, '4046_units'), (0.07472357489703418, 'xl_bags'), (0.0653161627824877, 'avg_price_current_year'), (0.05894226732599109, '4770_units'), (0.05452787322276258, 'total_bags'), (0.04361970804410779, 'type'), (0.04348611775865924, 's_bags'), (0.0417820227248063, '4225_units'), (0.03745487504500644, 'l_bags'), (0.01931991684522804, 'avg_price_prior_year'), (0.015346070390612252, 'avg_price_variance'), (0.010565843710266419, 'unit_variance'), (0.010225994781254853, 'dollars_current_year'), (0.010020896195985615, 'dollars_prior_year'), (0.008693786400873928, 'units_current_year'), (0.007654674164286661, 'units_prior_year'), (0.007620084914191139, 'sp09'), (0.007212077560967422, 'phdi'), (0.006532511481827212, 'pmdi'), (0.005310573505469217, 'sp06'), (0.004458076711897504, 'dollar_variance'), (0.004391799222197901, 'sp12'), (0.004161253874932447, 'tmin'), (0.004081714738616909, 'peru'), (0.004033268854931417, 'pdsi'), (0.003921729896669362, 'cdd'), (0.003664036043005918, 'tmax'), (0.003327972990145323, 'hdd'), (0.003195825497828278, 'tavg'), (0.00311889083216851, 'sp03'), (0.0028816872100627154, 'mexico'), (0.0024816525649427076, 'pcp'), (0.002330144735215537, 'california'), (0.0023062765940454195, 'geography_San Francisco'), (0.0020498943497255086, 'year_month_2019-07-01 00:00:00'), (0.00184783653574041, 'sp24'), (0.001792336525105543, 'geography_Hartford/Springfield'), (0.0017331437595975087, 'period'), (0.0014028930197062983, 'sp02'), (0.0012529292992921174, 'geography_Northeast'), (0.001239846933721477, 'zndx'), (0.0010800604742572557, 'chile'), (0.0010191537023113084, 'geography_New York'), (0.0010006289451271965, 'geography_Seattle'), (0.0009752596881513412, 'geography_California'), (0.0009365096492307919, 'geography_Spokane'), (0.0009361677366104649, 'sp01'), (0.0008516169415217359, 'geography_Total U.S.'), (0.0007908845059911989, 'geography_Houston'), (0.0007425023087880852, 'geography_Boston'), (0.0006577439664066902, 'geography_Baltimore/Washington'), (0.0006361893339259716, 'geography_Grand Rapids'), (0.0006216826268953113, 'geography_New Orleans/Mobile'), (0.0005953847297335699, 'geography_Tampa'), (0.0005507845152972996, 'geography_Portland'), (0.0005184468623491626, 'geography_Boise'), (0.000511684978164772, 'geography_Raleigh/Greensboro'), (0.0004871203475226887, 'year_month_2019-08-01 00:00:00'), (0.0004868849109272574, 'geography_West Tex/New Mexico'), (0.00047817912523713296, 'geography_Philadelphia'), (0.00046938533581524975, 'columbia'), (0.00046624104225206735, 'geography_Dallas/Ft. Worth'), (0.0004461952659466187, 'geography_St. Louis'), (0.000428599864700269, 'geography_Syracuse'), (0.0004208139162498989, 'geography_San Diego'), (0.0004186520986173117, 'geography_Buffalo/Rochester'), (0.0004165290139737403, 'geography_South Central'), (0.0003497797247367974, 'year_month_2018-09-01 00:00:00'), (0.00034417279462723685, 'year_month_2019-12-01 00:00:00'), (0.00033175532687983926, 'geography_Pittsburgh'), (0.00031780268269607074, 'year_month_2020-08-01 00:00:00'), (0.0002986344300456919, 'geography_West'), (0.0002906578941807739, 'geography_Chicago'), (0.0002848432443636482, 'geography_Charlotte'), (0.00026231117168707264, 'geography_Phoenix/Tucson'), (0.00025289643451412093, 'geography_Sacramento'), (0.00025109692045674915, 'geography_Harrisburg/Scranton'), (0.000248673075071981, 'geography_Columbus'), (0.000245510781502111, 'geography_Louisville'), (0.00021302044352810936, 'geography_Albany'), (0.0001902173714438258, 'year_month_2020-02-01 00:00:00'), (0.00018520307650999075, 'year_month_2019-05-01 00:00:00'), (0.00017754773533715126, 'geography_Richmond/Norfolk'), (0.000158993381997763, 'geography_Atlanta'), (0.0001548595229033318, 'year_month_2019-03-01 00:00:00'), (0.00014411713765525037, 'date_2019-07-21 00:00:00'), (0.0001437191974280205, 'geography_Orlando'), (0.00014338005162972724, 'geography_Jacksonville'), (0.0001313476381953327, 'date_2018-12-02 00:00:00'), (0.000129051349651654, 'year_month_2019-10-01 00:00:00'), (0.0001232398921397096, 'geography_Great Lakes'), (0.00012322613858540394, 'date_2019-04-28 00:00:00'), (0.00012173330610099853, 'geography_Plains'), (0.00011856150574384069, 'geography_Midsouth'), (0.0001157634707860939, 'geography_Nashville'), (0.00010899701984289308, 'geography_Los Angeles'), (0.00010610327837107148, 'geography_Indianapolis'), (0.00010579691054797578, 'year_month_2019-11-01 00:00:00'), (0.00010106262962644399, 'geography_Southeast'), (9.990399164462761e-05, 'year_month_2019-02-01 00:00:00'), (9.854044096898882e-05, 'year_month_2018-12-01 00:00:00'), (9.154786953423179e-05, 'year_month_2019-06-01 00:00:00'), (8.67756602566204e-05, 'year_month_2019-09-01 00:00:00'), (7.897732763225882e-05, 'geography_Northern New England'), (7.439992970792214e-05, 'year_month_2020-01-01 00:00:00'), (7.204323929981008e-05, 'date_2018-09-02 00:00:00'), (6.781672551040455e-05, 'year_month_2020-03-01 00:00:00'), (6.697733952068673e-05, 'geography_Roanoke'), (6.135197207642092e-05, 'year_month_2019-04-01 00:00:00'), (5.9867759792875e-05, 'geography_Detroit'), (5.843508068692809e-05, 'geography_Cincinnati/Dayton'), (5.4760465591409235e-05, 'year_month_2020-04-01 00:00:00'), (5.127697944790274e-05, 'geography_Las Vegas'), (4.6003465842855345e-05, 'year_month_2018-04-01 00:00:00'), (4.226962878047295e-05, 'date_2019-12-29 00:00:00'), (4.038951026330148e-05, 'year_month_2018-11-01 00:00:00'), (3.840945333105435e-05, 'year_month_2018-02-01 00:00:00'), (3.7730847593641716e-05, 'date_2019-04-21 00:00:00'), (3.770466122820682e-05, 'date_2018-11-25 00:00:00'), (3.580160099062204e-05, 'date_2019-07-28 00:00:00'), (3.489037602058893e-05, 'year_month_2018-08-01 00:00:00'), (3.398851418936667e-05, 'date_2019-10-27 00:00:00'), (3.373678726502963e-05, 'year_month_2018-01-01 00:00:00'), (3.063474723231321e-05, 'geography_Denver'), (3.063223169361168e-05, 'date_2019-06-23 00:00:00'), (3.0344285146769328e-05, 'date_2018-01-14 00:00:00'), (3.0173791250391082e-05, 'year_month_2018-10-01 00:00:00'), (2.8659932471099902e-05, 'date_2019-07-14 00:00:00'), (2.843281854859234e-05, 'date_2019-08-04 00:00:00'), (2.7176031948462094e-05, 'date_2019-12-01 00:00:00'), (2.7084415815529612e-05, 'date_2019-11-03 00:00:00'), (2.5756518476683423e-05, 'year_month_2018-05-01 00:00:00'), (2.549479088809571e-05, 'geography_South Carolina'), (2.4620716023657783e-05, 'date_2019-07-07 00:00:00'), (2.4559408629052365e-05, 'date_2019-12-08 00:00:00'), (2.3618879124652006e-05, 'date_2018-09-09 00:00:00'), (2.315316011986551e-05, 'date_2018-05-06 00:00:00'), (2.2747104405292572e-05, 'year_month_2020-07-01 00:00:00'), (2.2321906768457892e-05, 'date_2019-06-02 00:00:00'), (2.085692947759669e-05, 'date_2019-06-30 00:00:00'), (1.9732932995054722e-05, 'date_2019-12-15 00:00:00'), (1.7640708433536494e-05, 'year_month_2018-06-01 00:00:00'), (1.6873226293079686e-05, 'date_2019-04-14 00:00:00'), (1.6379382303513716e-05, 'date_2019-08-11 00:00:00'), (1.5734959394542552e-05, 'date_2020-03-08 00:00:00'), (1.5312663189354177e-05, 'year_month_2020-06-01 00:00:00'), (1.4872723879968258e-05, 'date_2020-02-09 00:00:00'), (1.4424293516047873e-05, 'date_2019-05-26 00:00:00'), (1.4110071760606577e-05, 'date_2020-02-23 00:00:00'), (1.3892476686346593e-05, 'date_2020-09-06 00:00:00'), (1.3815868590448275e-05, 'year_month_2020-09-01 00:00:00'), (1.3421558827634441e-05, 'date_2018-07-29 00:00:00'), (1.3393642505223482e-05, 'date_2019-05-05 00:00:00'), (1.3312913477785065e-05, 'date_2020-03-15 00:00:00'), (1.3082313930615252e-05, 'date_2018-04-01 00:00:00'), (1.2950668927972416e-05, 'date_2018-02-04 00:00:00'), (1.2896671637619301e-05, 'date_2019-08-25 00:00:00'), (1.2633543379037455e-05, 'date_2019-11-24 00:00:00'), (1.254443977326139e-05, 'date_2019-06-09 00:00:00'), (1.2225845311363611e-05, 'date_2019-02-03 00:00:00'), (1.2065833695100508e-05, 'date_2018-02-18 00:00:00'), (1.1973410740437798e-05, 'date_2020-02-02 00:00:00'), (1.1966544760046985e-05, 'date_2020-04-12 00:00:00'), (1.1718130915834509e-05, 'date_2019-06-16 00:00:00'), (1.1571098085787578e-05, 'date_2019-10-06 00:00:00'), (1.1325434868444134e-05, 'date_2019-05-12 00:00:00'), (1.1261314055371394e-05, 'date_2020-05-17 00:00:00'), (1.1246472528998804e-05, 'date_2018-02-25 00:00:00'), (1.1212547310806816e-05, 'date_2019-11-17 00:00:00'), (1.113377728682332e-05, 'date_2018-01-07 00:00:00'), (1.0924058003852283e-05, 'date_2018-09-30 00:00:00'), (1.0603227119488687e-05, 'date_2020-08-30 00:00:00'), (1.0547723295300844e-05, 'date_2019-02-17 00:00:00'), (1.0546934293007162e-05, 'date_2019-02-10 00:00:00'), (1.0369150995359676e-05, 'date_2019-04-07 00:00:00'), (1.0241921662108362e-05, 'date_2018-03-04 00:00:00'), (1.0080788696693212e-05, 'date_2020-08-16 00:00:00'), (9.997676940759522e-06, 'date_2019-01-27 00:00:00'), (9.912334557168625e-06, 'date_2020-03-01 00:00:00'), (9.8838722359175e-06, 'date_2018-01-21 00:00:00'), (9.664263005827575e-06, 'date_2019-03-24 00:00:00'), (9.633805211793552e-06, 'year_month_2018-07-01 00:00:00'), (9.607876085557354e-06, 'date_2020-07-26 00:00:00'), (9.354982569300537e-06, 'date_2020-08-23 00:00:00'), (8.7822024648851e-06, 'year_month_2020-05-01 00:00:00'), (8.66366483680959e-06, 'year_month_2018-03-01 00:00:00'), (8.638461829273824e-06, 'date_2018-06-24 00:00:00'), (8.255475793177492e-06, 'date_2018-10-21 00:00:00'), (8.170403440886484e-06, 'date_2020-01-19 00:00:00'), (8.162262777106499e-06, 'date_2018-04-22 00:00:00'), (7.936046211735068e-06, 'date_2019-09-15 00:00:00'), (7.77302675612921e-06, 'date_2018-11-18 00:00:00'), (7.687326598343132e-06, 'year_month_2019-01-01 00:00:00'), (7.670536384306145e-06, 'date_2020-07-12 00:00:00'), (7.668656431447087e-06, 'date_2019-10-13 00:00:00'), (7.650383380868811e-06, 'date_2020-02-16 00:00:00'), (7.521199581573895e-06, 'date_2018-02-11 00:00:00'), (7.506140218837321e-06, 'date_2019-03-17 00:00:00'), (7.3844482287485315e-06, 'date_2020-05-24 00:00:00'), (7.362451023524084e-06, 'date_2018-01-28 00:00:00'), (7.193639758322278e-06, 'date_2018-09-23 00:00:00'), (6.944209107089686e-06, 'date_2018-10-07 00:00:00'), (6.6732894872372105e-06, 'date_2019-03-03 00:00:00'), (6.667905552827667e-06, 'date_2018-03-18 00:00:00'), (6.554962018829462e-06, 'date_2018-04-29 00:00:00'), (6.400362171094808e-06, 'date_2019-10-20 00:00:00'), (5.93296776163448e-06, 'date_2020-04-05 00:00:00'), (5.789429542718735e-06, 'date_2019-11-10 00:00:00'), (5.779634256415388e-06, 'date_2020-05-31 00:00:00'), (5.735839539759274e-06, 'date_2020-01-12 00:00:00'), (5.66510132529375e-06, 'date_2019-08-18 00:00:00'), (5.6599230459326115e-06, 'date_2018-08-26 00:00:00'), (5.541810034280622e-06, 'date_2018-04-08 00:00:00'), (5.307626894648416e-06, 'date_2019-05-19 00:00:00'), (5.241278109399005e-06, 'date_2020-08-02 00:00:00'), (5.04779979620812e-06, 'date_2019-09-29 00:00:00'), (4.921030176755204e-06, 'date_2018-10-14 00:00:00'), (4.708183133337479e-06, 'date_2018-03-25 00:00:00'), (4.669766622542393e-06, 'date_2019-12-22 00:00:00'), (4.518708272866165e-06, 'date_2019-01-20 00:00:00'), (4.376229605524541e-06, 'date_2018-11-11 00:00:00'), (4.2762632645383705e-06, 'date_2020-05-03 00:00:00'), (4.270291957771755e-06, 'date_2018-09-16 00:00:00'), (4.051597970414282e-06, 'date_2018-10-28 00:00:00'), (3.7446794525904835e-06, 'date_2019-09-08 00:00:00'), (3.613488842831739e-06, 'date_2019-09-22 00:00:00'), (3.537189192108199e-06, 'date_2019-01-13 00:00:00'), (3.431840675373441e-06, 'date_2020-03-29 00:00:00'), (3.390951537961988e-06, 'date_2020-06-28 00:00:00'), (3.3040354779720596e-06, 'date_2018-05-27 00:00:00'), (3.2700572639638247e-06, 'date_2020-01-26 00:00:00'), (3.1206722208535835e-06, 'date_2019-03-10 00:00:00'), (3.1038251637977603e-06, 'date_2020-06-14 00:00:00'), (2.9664655292813235e-06, 'date_2019-09-01 00:00:00'), (2.9284897767292875e-06, 'date_2018-07-22 00:00:00'), (2.471792451078594e-06, 'date_2020-04-26 00:00:00'), (2.4542344761024205e-06, 'date_2018-05-13 00:00:00'), (2.237794155025991e-06, 'date_2019-03-31 00:00:00'), (2.224298408383977e-06, 'date_2020-05-10 00:00:00'), (2.18012598033048e-06, 'date_2018-11-04 00:00:00'), (2.172267634300273e-06, 'date_2018-06-03 00:00:00'), (2.130260403423521e-06, 'date_2018-08-19 00:00:00'), (2.034719234139617e-06, 'date_2020-06-07 00:00:00'), (1.772835345078461e-06, 'date_2018-07-01 00:00:00'), (1.7375580467586052e-06, 'date_2020-06-21 00:00:00'), (1.4600491181599671e-06, 'date_2018-03-11 00:00:00'), (1.4090995110129122e-06, 'date_2020-08-09 00:00:00'), (1.3631729474307804e-06, 'date_2018-08-12 00:00:00'), (1.040482199357889e-06, 'date_2018-07-08 00:00:00'), (9.973328787571577e-07, 'date_2020-03-22 00:00:00'), (9.904877278652085e-07, 'date_2018-04-15 00:00:00'), (9.188583461640546e-07, 'date_2020-04-19 00:00:00'), (5.962591048499266e-07, 'date_2018-08-05 00:00:00'), (5.17714005526956e-07, 'date_2019-02-24 00:00:00'), (0.0, 'variety'), (0.0, 'status'), (0.0, 'segment'), (0.0, 'date_2020-07-19 00:00:00'), (0.0, 'date_2020-07-05 00:00:00'), (0.0, 'date_2018-07-15 00:00:00'), (0.0, 'date_2018-06-17 00:00:00'), (0.0, 'date_2018-06-10 00:00:00'), (0.0, 'date_2018-05-20 00:00:00')]

In [11]:
y = cleaned_cat_df['price_cat']
X = cleaned_cat_df.drop(columns=['price_cat', 'avg_price', 'total_volume_prod', 'total_volume_price'], axis=1)

RFSSModel4(X, y)

Predictions: ['3' '0' '3' ... '2' '0' '2']
Confusion Matrix

          Predicted 0  Predicted 1  Predicted 2  Predicted 3
Actual 0          877           82           57           17
Actual 1          350          283          260           57
Actual 2          101          147          551          172
Actual 3           16           39          195          506

Accuracy Score : 0.5975741239892183
Classification Report
              precision    recall  f1-score   support

           0       0.65      0.85      0.74      1033
           1       0.51      0.30      0.38       950
           2       0.52      0.57      0.54       971
           3       0.67      0.67      0.67       756

    accuracy                           0.60      3710
   macro avg       0.59      0.60      0.58      3710
weighted avg       0.59      0.60      0.58      3710

Importances: [6.06437409e-02 1.08313855e-01 5.80785601e-02 7.38218975e-02
 8.17983179e-02 6.85955246e-02 5.87508358e-02 1.02358736e-01
 3.68180670e-03 4.75631422e-03 5.99983972e-03 9.67685534e-03
 1.96918677e-03 8.29046411e-03 5.98247336e-03 4.67655329e-03
 1.22022080e-03 2.41216432e-03 4.43469889e-03 7.67913619e-03
 1.16746497e-02 6.56429479e-03 2.85111424e-03 6.40571022e-03
 4.98865101e-03 0.00000000e+00 3.09184261e-03 1.74164274e-03
 4.16107856e-03 6.12210913e-03 9.88367903e-04 0.00000000e+00
 0.00000000e+00 2.20898385e-03 1.08181070e-02 1.22577709e-02
 1.55276355e-02 1.49328954e-02 1.55853331e-02 6.91543406e-03
 2.95569660e-02 1.04328822e-01 2.14905646e-02 1.02822263e-04
 3.36274264e-05 7.78042231e-06 5.75408764e-05 5.38669977e-05
 5.80270514e-05 1.10969143e-05 1.57817364e-05 6.18808238e-04
 3.24500239e-05 2.50964559e-05 2.40323262e-04 1.94284165e-05
 8.38977287e-05 9.01018079e-05 1.54945360e-04 2.39108432e-04
 1.51336786e-04 2.69163152e-03 6.67855898e-04 3.12787486e-05
 1.07888616e-04 6.67094824e-05 7.34934383e-04 5.87800568e-05
 2.50551352e-04 8.84925703e-05 7.29556382e-05 1.23166998e-05
 2.18480401e-05 3.05368371e-05 3.72824591e-04 1.48541067e-05
 1.65230729e-05 3.61811457e-05 1.97299064e-05 1.66902828e-05
 3.39951577e-05 1.22106448e-05 2.62951296e-05 1.68164221e-05
 1.41182855e-06 4.73753797e-06 2.56796472e-05 1.16586163e-05
 1.10490179e-05 1.04096121e-05 1.49241491e-06 3.12189351e-05
 7.47025406e-06 2.42759618e-05 7.46613272e-07 7.34712296e-06
 9.97060172e-06 1.39968221e-05 1.34771947e-05 1.37527258e-06
 9.88900152e-06 6.33576028e-06 8.09096511e-06 2.11555927e-06
 4.48595289e-06 8.33010725e-06 1.55221937e-05 6.37639556e-06
 1.73487309e-06 2.58897355e-05 4.32374454e-05 2.72190795e-05
 1.24995296e-06 2.06268616e-05 1.03108856e-05 9.81649961e-06
 1.02444986e-05 5.66023201e-07 2.24081304e-05 1.82221510e-05
 7.54450962e-06 9.52397969e-06 3.60504090e-05 1.99758827e-04
 1.81175281e-05 7.20899091e-06 8.47770357e-06 7.29379814e-06
 2.56155335e-05 9.71288205e-06 1.19227481e-06 3.29889384e-05
 6.22777485e-06 2.16420968e-05 1.14762795e-05 3.31661704e-06
 6.42217792e-05 2.38017692e-05 5.72098454e-05 2.41332516e-04
 1.81294611e-05 8.11421147e-06 4.92928575e-06 1.49161268e-05
 2.85835180e-05 1.08303207e-05 1.25082144e-05 2.71419987e-05
 3.59461458e-05 6.80654145e-05 4.38588576e-05 2.50142619e-04
 7.22663639e-05 7.05005721e-05 1.13455747e-05 2.59608353e-05
 1.31396314e-05 1.93057778e-05 1.66039245e-05 4.28445254e-06
 4.35538140e-06 4.84098497e-06 1.75764712e-06 8.29708874e-06
 1.02038952e-05 2.42307900e-05 3.55215345e-05 2.82030601e-06
 1.96388828e-05 9.37603681e-07 1.84385569e-05 4.57699695e-05
 2.57852208e-05 2.62867245e-05 5.76031614e-05 1.86157240e-05
 5.87594872e-06 4.11383270e-06 1.68468943e-05 2.90215545e-06
 1.14108466e-05 1.40898174e-05 2.15576297e-05 7.32941710e-06
 2.02630349e-05 4.24387501e-06 3.28253462e-05 5.23951652e-06
 8.61105322e-06 0.00000000e+00 1.21827017e-05 1.42437506e-05
 3.13828333e-06 1.84635499e-05 0.00000000e+00 1.43128017e-06
 4.91345715e-06 1.39730613e-06 6.38418877e-06 5.33396313e-06
 2.02889514e-06 9.50032827e-07 7.91538850e-06 5.77043926e-06
 3.52067844e-09 1.62576338e-05 3.97302448e-06 8.91084295e-06
 3.92943607e-06 1.46923520e-05 1.90418986e-04 1.45262730e-04
 1.30077064e-03 7.84982135e-04 1.00241850e-03 8.34999217e-04
 1.47969980e-03 2.56283446e-04 4.53367745e-04 6.15993730e-05
 2.67615192e-04 8.92275301e-04 4.54312664e-05 1.44548846e-04
 7.94042381e-04 1.39834742e-04 2.96898619e-04 2.30887543e-03
 1.28259626e-03 1.95006670e-04 1.96668512e-04 1.20040842e-04
 2.18087904e-04 2.77628094e-04 1.45080468e-04 2.35918185e-04
 9.41837418e-04 1.90393984e-03 1.76027160e-03 1.21607531e-04
 2.52227706e-04 8.60972770e-04 4.87496183e-04 3.58797953e-04
 1.57135107e-04 6.60666646e-04 6.73162638e-04 2.42456272e-04
 1.43182252e-04 3.95250383e-04 4.85322019e-04 3.51821942e-03
 1.87853619e-03 3.35239790e-05 6.19658558e-04 1.86140764e-04
 9.90167489e-04 8.30832290e-04 6.40480658e-04 6.64114899e-04
 7.46621659e-04 3.51101771e-04 7.04219545e-04]
[(0.10831385455503077, '4046_units'), (0.10432882228872929, 'avg_price_current_year'), (0.10235873613595393, 'xl_bags'), (0.08179831792650927, 'total_bags'), (0.0738218975456134, '4770_units'), (0.06859552460493511, 's_bags'), (0.06064374094456864, 'type'), (0.05875083584917236, 'l_bags'), (0.0580785601286949, '4225_units'), (0.029556965992957072, 'avg_price_prior_year'), (0.02149056455282613, 'avg_price_variance'), (0.01558533305009481, 'dollars_current_year'), (0.015527635505961238, 'unit_variance'), (0.014932895388368905, 'dollars_prior_year'), (0.012257770934240525, 'units_current_year'), (0.01167464967729345, 'sp09'), (0.010818106974131332, 'units_prior_year'), (0.00967685534438454, 'phdi'), (0.00829046411255433, 'pmdi'), (0.007679136193247214, 'sp06'), (0.006915434063423748, 'dollar_variance'), (0.006564294793640388, 'sp12'), (0.006405710220942087, 'tmin'), (0.006122109125581284, 'peru'), (0.005999839719212407, 'pdsi'), (0.005982473355855274, 'cdd'), (0.004988651009855222, 'tmax'), (0.004756314217543219, 'tavg'), (0.004676553289584023, 'hdd'), (0.004434698886140251, 'sp03'), (0.004161078562446388, 'mexico'), (0.003681806703983811, 'pcp'), (0.003518219424543553, 'geography_San Francisco'), (0.0030918426139922577, 'california'), (0.002851114241868701, 'sp24'), (0.0026916315215008953, 'year_month_2019-07-01 00:00:00'), (0.0024121643163474015, 'sp02'), (0.002308875433510643, 'geography_Hartford/Springfield'), (0.0022089838503243833, 'period'), (0.0019691867662166304, 'zndx'), (0.0019039398442142288, 'geography_New York'), (0.0018785361904765261, 'geography_Seattle'), (0.0017602715997789666, 'geography_Northeast'), (0.0017416427398785567, 'chile'), (0.0014796998037851633, 'geography_California'), (0.001300770639001778, 'geography_Baltimore/Washington'), (0.0012825962629059938, 'geography_Houston'), (0.0012202207984085005, 'sp01'), (0.0010024185043407043, 'geography_Boston'), (0.0009901674889983582, 'geography_Spokane'), (0.0009883679028156447, 'columbia'), (0.000941837417627861, 'geography_New Orleans/Mobile'), (0.0008922753010113858, 'geography_Dallas/Ft. Worth'), (0.0008609727696435146, 'geography_Philadelphia'), (0.000834999216908447, 'geography_Buffalo/Rochester'), (0.000830832290134279, 'geography_St. Louis'), (0.0007940423811674441, 'geography_Grand Rapids'), (0.0007849821346458108, 'geography_Boise'), (0.000746621658669687, 'geography_Total U.S.'), (0.0007349343833699387, 'year_month_2019-12-01 00:00:00'), (0.0007042195451237841, 'geography_West Tex/New Mexico'), (0.0006731626379078912, 'geography_Raleigh/Greensboro'), (0.0006678558984043386, 'year_month_2019-08-01 00:00:00'), (0.0006641148992643678, 'geography_Tampa'), (0.0006606666459196902, 'geography_Portland'), (0.0006404806579170194, 'geography_Syracuse'), (0.0006196585575120409, 'geography_South Central'), (0.0006188082382709542, 'year_month_2018-09-01 00:00:00'), (0.00048749618340588783, 'geography_Phoenix/Tucson'), (0.000485322018666314, 'geography_San Diego'), (0.00045336774455183017, 'geography_Chicago'), (0.0003952503825055848, 'geography_Sacramento'), (0.0003728245906936401, 'year_month_2020-08-01 00:00:00'), (0.0003587979527860889, 'geography_Pittsburgh'), (0.00035110177082221225, 'geography_West'), (0.00029689861898359764, 'geography_Harrisburg/Scranton'), (0.00027762809418757433, 'geography_Louisville'), (0.0002676151924003998, 'geography_Columbus'), (0.00025628344621403393, 'geography_Charlotte'), (0.0002522277055853817, 'geography_Orlando'), (0.0002505513516281812, 'year_month_2020-02-01 00:00:00'), (0.0002501426192924061, 'date_2019-07-21 00:00:00'), (0.00024245627156008935, 'geography_Richmond/Norfolk'), (0.00024133251560521502, 'date_2019-04-28 00:00:00'), (0.0002403232623099738, 'year_month_2018-12-01 00:00:00'), (0.00023910843169185013, 'year_month_2019-05-01 00:00:00'), (0.00023591818506367763, 'geography_Nashville'), (0.00021808790396255545, 'geography_Los Angeles'), (0.000199758827162937, 'date_2018-12-02 00:00:00'), (0.00019666851225992108, 'geography_Jacksonville'), (0.0001950066703154223, 'geography_Indianapolis'), (0.00019041898581811226, 'geography_Albany'), (0.0001861407643237534, 'geography_Southeast'), (0.00015713510654076387, 'geography_Plains'), (0.00015494535993465435, 'year_month_2019-04-01 00:00:00'), (0.00015133678554927644, 'year_month_2019-06-01 00:00:00'), (0.00014526273024355202, 'geography_Atlanta'), (0.0001450804682573682, 'geography_Midsouth'), (0.00014454884617772396, 'geography_Detroit'), (0.00014318225213392742, 'geography_Roanoke'), (0.0001398347416191515, 'geography_Great Lakes'), (0.00012160753065449362, 'geography_Northern New England'), (0.00012004084247899651, 'geography_Las Vegas'), (0.00010788861559893134, 'year_month_2019-10-01 00:00:00'), (0.0001028222630139364, 'year_month_2018-01-01 00:00:00'), (9.010180791816973e-05, 'year_month_2019-03-01 00:00:00'), (8.849257032979837e-05, 'year_month_2020-03-01 00:00:00'), (8.389772874233263e-05, 'year_month_2019-02-01 00:00:00'), (7.295563818722772e-05, 'year_month_2020-04-01 00:00:00'), (7.226636387086301e-05, 'date_2019-07-28 00:00:00'), (7.05005720672641e-05, 'date_2019-08-04 00:00:00'), (6.80654145351185e-05, 'date_2019-07-07 00:00:00'), (6.67094824168335e-05, 'year_month_2019-11-01 00:00:00'), (6.422177919927584e-05, 'date_2019-04-07 00:00:00'), (6.159937298813156e-05, 'geography_Cincinnati/Dayton'), (5.8780056788714054e-05, 'year_month_2020-01-01 00:00:00'), (5.8027051365164636e-05, 'year_month_2018-06-01 00:00:00'), (5.760316140697838e-05, 'date_2019-12-29 00:00:00'), (5.754087636260562e-05, 'year_month_2018-04-01 00:00:00'), (5.720984543715726e-05, 'date_2019-04-21 00:00:00'), (5.386699770000791e-05, 'year_month_2018-05-01 00:00:00'), (4.576996945469869e-05, 'date_2019-12-08 00:00:00'), (4.5431266397297355e-05, 'geography_Denver'), (4.385885758331082e-05, 'date_2019-07-14 00:00:00'), (4.323744538076551e-05, 'date_2018-09-02 00:00:00'), (3.61811457470368e-05, 'date_2018-01-14 00:00:00'), (3.605040898001964e-05, 'date_2018-11-25 00:00:00'), (3.594614583065751e-05, 'date_2019-06-30 00:00:00'), (3.552153447908818e-05, 'date_2019-11-03 00:00:00'), (3.3995157673567266e-05, 'date_2018-02-04 00:00:00'), (3.362742637034293e-05, 'year_month_2018-02-01 00:00:00'), (3.3523978969893036e-05, 'geography_South Carolina'), (3.298893835609546e-05, 'date_2019-03-03 00:00:00'), (3.282534624558461e-05, 'date_2020-03-29 00:00:00'), (3.2450023943764725e-05, 'year_month_2018-10-01 00:00:00'), (3.127874857359292e-05, 'year_month_2019-09-01 00:00:00'), (3.121893505276842e-05, 'date_2018-04-22 00:00:00'), (3.053683706723832e-05, 'year_month_2020-07-01 00:00:00'), (2.858351797340396e-05, 'date_2019-06-02 00:00:00'), (2.7219079470509093e-05, 'date_2018-09-09 00:00:00'), (2.7141998744599084e-05, 'date_2019-06-23 00:00:00'), (2.629512960729816e-05, 'date_2018-02-18 00:00:00'), (2.628672449909796e-05, 'date_2019-12-22 00:00:00'), (2.5960835277221994e-05, 'date_2019-08-18 00:00:00'), (2.588973554175317e-05, 'date_2018-08-26 00:00:00'), (2.578522081307796e-05, 'date_2019-12-15 00:00:00'), (2.5679647222371986e-05, 'date_2018-03-18 00:00:00'), (2.561553350726196e-05, 'date_2019-02-10 00:00:00'), (2.5096455891117563e-05, 'year_month_2018-11-01 00:00:00'), (2.4275961781174922e-05, 'date_2018-05-06 00:00:00'), (2.4230790018844983e-05, 'date_2019-10-27 00:00:00'), (2.3801769241673657e-05, 'date_2019-04-14 00:00:00'), (2.2408130395885654e-05, 'date_2018-10-28 00:00:00'), (2.18480400720319e-05, 'year_month_2020-06-01 00:00:00'), (2.1642096790934175e-05, 'date_2019-03-17 00:00:00'), (2.155762974813306e-05, 'date_2020-03-01 00:00:00'), (2.062686158284738e-05, 'date_2018-09-23 00:00:00'), (2.0263034941342963e-05, 'date_2020-03-15 00:00:00'), (1.9729906358685194e-05, 'date_2018-01-21 00:00:00'), (1.9638882822937523e-05, 'date_2019-11-17 00:00:00'), (1.9428416465758697e-05, 'year_month_2019-01-01 00:00:00'), (1.9305777790844377e-05, 'date_2019-09-01 00:00:00'), (1.861572404716949e-05, 'date_2020-01-12 00:00:00'), (1.8463549879670026e-05, 'date_2020-05-17 00:00:00'), (1.843855686944717e-05, 'date_2019-12-01 00:00:00'), (1.8222150966962594e-05, 'date_2018-11-04 00:00:00'), (1.8129461069867526e-05, 'date_2019-05-05 00:00:00'), (1.811752808999008e-05, 'date_2019-01-13 00:00:00'), (1.6846894336217026e-05, 'date_2020-02-02 00:00:00'), (1.6816422138659267e-05, 'date_2018-02-25 00:00:00'), (1.6690282815064283e-05, 'date_2018-01-28 00:00:00'), (1.6603924505483155e-05, 'date_2019-09-08 00:00:00'), (1.6523072931824013e-05, 'date_2018-01-07 00:00:00'), (1.62576338398772e-05, 'date_2020-08-09 00:00:00'), (1.578173644809456e-05, 'year_month_2018-08-01 00:00:00'), (1.5522193675048717e-05, 'date_2018-08-05 00:00:00'), (1.491612676800256e-05, 'date_2019-05-26 00:00:00'), (1.485410665246297e-05, 'year_month_2020-09-01 00:00:00'), (1.4692352036336288e-05, 'date_2020-09-06 00:00:00'), (1.4243750615607148e-05, 'date_2020-05-03 00:00:00'), (1.4089817445521947e-05, 'date_2020-02-23 00:00:00'), (1.3996822093246321e-05, 'date_2018-06-03 00:00:00'), (1.347719469516299e-05, 'date_2018-06-10 00:00:00'), (1.3139631395270724e-05, 'date_2019-08-25 00:00:00'), (1.2508214428881416e-05, 'date_2019-06-16 00:00:00'), (1.2316699843614999e-05, 'year_month_2020-05-01 00:00:00'), (1.2210644772573806e-05, 'date_2018-02-11 00:00:00'), (1.2182701731158293e-05, 'date_2020-04-26 00:00:00'), (1.1658616253470294e-05, 'date_2018-03-25 00:00:00'), (1.1476279476199607e-05, 'date_2019-03-24 00:00:00'), (1.1410846612652661e-05, 'date_2020-02-16 00:00:00'), (1.134557466163717e-05, 'date_2019-08-11 00:00:00'), (1.1096914288420125e-05, 'year_month_2018-07-01 00:00:00'), (1.1049017859183452e-05, 'date_2018-04-01 00:00:00'), (1.0830320668452056e-05, 'date_2019-06-09 00:00:00'), (1.0409612071775223e-05, 'date_2018-04-08 00:00:00'), (1.0310885588659091e-05, 'date_2018-09-30 00:00:00'), (1.024449858179742e-05, 'date_2018-10-14 00:00:00'), (1.0203895200609374e-05, 'date_2019-10-20 00:00:00'), (9.970601717135195e-06, 'date_2018-05-27 00:00:00'), (9.889001517945335e-06, 'date_2018-06-24 00:00:00'), (9.816499607671096e-06, 'date_2018-10-07 00:00:00'), (9.712882053955047e-06, 'date_2019-02-17 00:00:00'), (9.523979690005373e-06, 'date_2018-11-18 00:00:00'), (8.910842951294473e-06, 'date_2020-08-23 00:00:00'), (8.611053215325885e-06, 'date_2020-04-12 00:00:00'), (8.477703573785687e-06, 'date_2019-01-27 00:00:00'), (8.33010725073774e-06, 'date_2018-07-29 00:00:00'), (8.29708874427072e-06, 'date_2019-10-13 00:00:00'), (8.114211471908312e-06, 'date_2019-05-12 00:00:00'), (8.090965112607391e-06, 'date_2018-07-08 00:00:00'), (7.915388501689166e-06, 'date_2020-07-19 00:00:00'), (7.780422314375383e-06, 'year_month_2018-03-01 00:00:00'), (7.5445096236701185e-06, 'date_2018-11-11 00:00:00'), (7.4702540611752575e-06, 'date_2018-04-29 00:00:00'), (7.347122964648009e-06, 'date_2018-05-20 00:00:00'), (7.329417102863481e-06, 'date_2020-03-08 00:00:00'), (7.2937981400854554e-06, 'date_2019-02-03 00:00:00'), (7.208990913877552e-06, 'date_2019-01-20 00:00:00'), (6.384188773830482e-06, 'date_2020-06-21 00:00:00'), (6.3763955588691285e-06, 'date_2018-08-12 00:00:00'), (6.3357602802294454e-06, 'date_2018-07-01 00:00:00'), (6.227774854255532e-06, 'date_2019-03-10 00:00:00'), (5.875948715281733e-06, 'date_2020-01-19 00:00:00'), (5.770439264925721e-06, 'date_2020-07-26 00:00:00'), (5.333963129058375e-06, 'date_2020-06-28 00:00:00'), (5.239516517550928e-06, 'date_2020-04-05 00:00:00'), (4.929285753662005e-06, 'date_2019-05-19 00:00:00'), (4.913457153777896e-06, 'date_2020-06-07 00:00:00'), (4.8409849651490705e-06, 'date_2019-09-29 00:00:00'), (4.73753797249256e-06, 'date_2018-03-11 00:00:00'), (4.485952889979333e-06, 'date_2018-07-22 00:00:00'), (4.355381401814485e-06, 'date_2019-09-22 00:00:00'), (4.2844525446530286e-06, 'date_2019-09-15 00:00:00'), (4.243875005109072e-06, 'date_2020-03-22 00:00:00'), (4.113832702178422e-06, 'date_2020-01-26 00:00:00'), (3.973024480113263e-06, 'date_2020-08-16 00:00:00'), (3.929436073777453e-06, 'date_2020-08-30 00:00:00'), (3.316617040196165e-06, 'date_2019-03-31 00:00:00'), (3.138283333989528e-06, 'date_2020-05-10 00:00:00'), (2.902155445477513e-06, 'date_2020-02-09 00:00:00'), (2.8203060149390253e-06, 'date_2019-11-10 00:00:00'), (2.11555926670756e-06, 'date_2018-07-15 00:00:00'), (2.028895136093832e-06, 'date_2020-07-05 00:00:00'), (1.7576471241108795e-06, 'date_2019-10-06 00:00:00'), (1.7348730925751992e-06, 'date_2018-08-19 00:00:00'), (1.4924149110936735e-06, 'date_2018-04-15 00:00:00'), (1.4312801662125665e-06, 'date_2020-05-31 00:00:00'), (1.411828550072805e-06, 'date_2018-03-04 00:00:00'), (1.3973061280716191e-06, 'date_2020-06-14 00:00:00'), (1.375272579728249e-06, 'date_2018-06-17 00:00:00'), (1.2499529614735882e-06, 'date_2018-09-16 00:00:00'), (1.1922748078185495e-06, 'date_2019-02-24 00:00:00'), (9.500328272152889e-07, 'date_2020-07-12 00:00:00'), (9.376036807120928e-07, 'date_2019-11-24 00:00:00'), (7.466132717551561e-07, 'date_2018-05-13 00:00:00'), (5.660232013134487e-07, 'date_2018-10-21 00:00:00'), (3.5206784398257734e-09, 'date_2020-08-02 00:00:00'), (0.0, 'variety'), (0.0, 'status'), (0.0, 'segment'), (0.0, 'date_2020-05-24 00:00:00'), (0.0, 'date_2020-04-19 00:00:00')]